import FloatingIcon from "@/components/floatingIcon";
import FooterSection from "@/components/home/footerSection";
import HeaderSection from "@/components/home/headerSection";
import SmoothScroll from "@/components/Shared/SmoothScroll";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`}>
        {/* Header should be outside SmoothScroll */}

        <SmoothScroll>
          <HeaderSection />
          {children}
          <FooterSection />
        </SmoothScroll>
        <FloatingIcon />
      </body>
    </html>
  );
}
