import type { Metadata } from "next";
import "../../globals.css";
import Image from "next/image";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <section className="container mx-auto -mt-1">
        {/* Form Section */}
        <div className="main-gradient flex flex-col items-center justify-around gap-10 rounded-tl-xl rounded-b-xl py-20 md:flex-row lg:px-40">
          <div className="w-full self-start md:w-[50%]">{children}</div>

          {/* Next Steps Flow */}
          <div className="space-y-6">
            <h2 className="text-muted-foreground text-2xl font-medium">
              Next Steps:
            </h2>
            <Image
              src="/assets/query-flow.png"
              alt="Next Steps Flow"
              width={500}
              height={500}
              className="w-[300px]"
            />
          </div>
        </div>
      </section>
      <Toaster position="top-center" />
    </main>
  );
}
