import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderSection from "@/components/home/headerSection";
import FooterSection from "@/components/home/footerSection";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderSection />
        {children}
        <FooterSection />

        {/* WhatsApp Floating Icon */}
        <a
          href="#"
          className="fixed bottom-4 right-4 z-50"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            src="/assets/whatsapp.svg"
            alt="WhatsApp"
            width={48}
            height={48}
          />
        </a>
      </body>
    </html>
  );
}
