import DashboardHeader from "@/components/dashboard/dashboardHeader";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`}>
        <DashboardHeader />
        {children}
      </body>
    </html>
  );
}
